### ISSUE TITLE
Error with Lexer.js using sample code

### ISSUE THREAD

**Issue by antman786** [apex-dev-tools/apex-parser#39]
I'm getting the following error when trying to parse some APEX code using the steps outlined in the readme.  I am using this version "@apexdevtools/apex-parser@3.6.0" of apex-parser and "antlr4ts@0.5.0-alpha.4" of antlr4ts. Please let me know if I'm doing something wrong.  
```
node_modules/antlr4ts/Lexer.js:87
        let tokenStartMarker = this._input.mark();
                                           ^

TypeError: this._input.mark is not a function
```

**Comment by pwrightcertinia** [comment]
This suggests the `CharStream` / object being passed in to the Lexer is not a `CaseInsensitiveInputStream` which I believe is where this method comes from. If you could post a code sample that would help narrow it down.

From the README, note the code string wrapped in `new CaseInsensitiveInputStream(...)`:
```
let lexer = new ApexLexer(new CaseInsensitiveInputStream("public class Hello {}"))
let tokens  = new CommonTokenStream(lexer);

let parser = new ApexParser(tokens)
let context = parser.compilationUnit()
```

I think that's most likely what is missing, first thing to check.

**Comment by antman786** [comment]
Here is my sample code where I'm passing in the absolute path of the .cls file locally.
```
async function generateAst(filePath) {
	const fileContents = await fs.readFile(filePath, 'utf-8');
	let lexer = new ApexLexer(new CaseInsensitiveInputStream(fileContents));
	let tokens = new CommonTokenStream(lexer);
	let parser = new ApexParser(tokens);
	let context = parser.compilationUnit();

	return context;
}
```

However, when I replace the fileContents with the sample you provided I get a different error than previously reported:
```
/node_modules/@apexdevtools/apex-parser/lib/CaseInsensitiveInputStream.js:46
        return this.src.mark();
                        ^

TypeError: this.src.mark is not a function
```

**Comment by adangel** [comment]
Try this:

```javascript
async function generateAst(filePath) {
	const fileContents = await fs.readFile(filePath, 'utf-8');
	let lexer = new ApexLexer(new CaseInsensitiveInputStream(CharStreams.fromString(fileContents)));
	let tokens = new CommonTokenStream(lexer);
	let parser = new ApexParser(tokens);
	let context = parser.compilationUnit();

	return context;
}
```

(I just looked at the unit tests, e.g. https://github.com/apex-dev-tools/apex-parser/blob/19ccabe5e07050e0a44284f9255509dfd996b3fe/npm/src/__tests__/ApexLexerTest.ts#L25 or https://github.com/apex-dev-tools/apex-parser/blob/19ccabe5e07050e0a44284f9255509dfd996b3fe/npm/src/__tests__/SyntaxErrorCounter.ts#L33-L36)

**Comment by antman786** [comment]
Thanks @adangel once I updated my imports to use CharStreams and CommonTokenStream from antlr4ts it worked.  I may have misread the instructions around compatibility and which package to import them from but it seems to be working now.

```
import { CharStreams, CommonTokenStream } from 'antlr4ts';
```
