### ISSUE TITLE
Apex SOQL failed with >2 nested sub-queries

### ISSUE THREAD

**Issue by nwcm** [apex-dev-tools/apex-parser#46]
Using Apex PMD 7.0.0 I ran into the below issue on a SOQL nested query. I updated to Apex PMD 7.4.0 to check if summit-ast (2.3.0)/apex-parser(4.1.0) solved this issue. With Apex PMD 7.4.0 it fails to scan however there are no debug or error outputs that are specific to the issue. 

## Error with PMD 7.0.0
![image](https://github.com/user-attachments/assets/6d437285-61bf-44ce-8d54-7bc060bd79f4)

## Error with PMD 7.4.0
```log
[TRACE] Processing file (lang: apex+version:60): c:\Users\x\repos\x\force-app\main\x\classes\x.cls
"Problem","Package","File","Priority","Line","Description","Rule set","Rule"
[INFO] An error occurred while executing PMD.
Run in verbose mode to see a stack-trace.
If you think this is a bug in PMD, please report this issue at https://github.com/pmd/pmd/issues/new/choose
If you do so, please include a stack-trace, the code sample
 causing the issue, and details about your run configuration.
```

Example Apex query
``` SQL
SELECT
        Id,
        Name,
        CreatedDate,
        (
          SELECT
            Id,
            Name,
            (
              SELECT Lookup__c.Name
              FROM Relationship__r
              WHERE RecordType.DeveloperName IN ('String', 'String')
              ORDER BY Lookup__c.Name
            )
          FROM Relationship__r
          WHERE
            Field__c = :var3
            OR Field2__c = TRUE
        )
      FROM CustomObject__c
      WHERE
        Field__c = :var1
        AND Field2__c IN :var2
      WITH USER_MODE
      LIMIT 1000
```

[sf docs](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_relationships_query_using.htm)

**Comment by pwrightcertinia** [comment]
Thank you for the contribution! Now released in version [`4.2.0`](https://github.com/apex-dev-tools/apex-parser/releases/tag/v4.2.0)
