### ISSUE TITLE
Parse error with GROUPING soql function

### ISSUE THREAD

**Issue by adangel** [apex-dev-tools/apex-parser#49]
Example code:

```
public class MyClassA3 {
    private List<AggregateResult> getDefects() {
        AggregateResult[] defects = [
            SELECT
              OBJ1__c O1,
              OBJ2__c O2,
              OBJ3__c O3,
              SUM(OBJ4__c) O4,
              GROUPING(OBJ1__c) O1Group,
              GROUPING(OBJ2__c) O2Group,
              GROUPING(OBJ3__c) O3Group
            FROM OBJ4__c
            GROUP BY ROLLUP(OBJ1__c, OBJ2__c, OBJ3__c)
        ];
        return defects;
    }
}
```

This fails to parse, as GROUPING is not supported by the grammar: https://github.com/apex-dev-tools/apex-parser/blob/fee3a16472601f7ca436506b5788ff86a0db9f69/antlr/ApexParser.g4#L614-L639

sf doc: https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_grouping.htm

Original issue: https://github.com/pmd/pmd/issues/5182

**Comment by pwrightcertinia** [comment]
Thank you for the contribution! Now released in version [`4.2.0`](https://github.com/apex-dev-tools/apex-parser/releases/tag/v4.2.0)
