### ISSUE TITLE
Lexing fails for string containing Unicode escape sequence

### ISSUE THREAD

**Issue by wahajenius** [apex-dev-tools/apex-parser#55]
The lexer does not correctly handle input strings containing a Unicode escape sequence like `'Fran\u00E7ois'`, due to `token recognition error`. Wrapping the input stream in a `CaseInsensitiveInputStream` makes it work though.

Here is a unit test demo:
~~~java
    @Test
    void testLexerUnicodeEscapes() {
        String s = "'Fran\\u00E7ois'";

        // Using a plain CodePointCharStream fails
        IllegalStateException exc = assertThrows(IllegalStateException.class, () -> {
            tryLexing(CharStreams.fromString(s));
        });
        assertEquals("Syntax error on line 1:0: token recognition error at: ''Fran\\u00E'.", exc.getMessage());

        // Wrapping it in a CaseInsensitiveInputStream makes it work. Why?
        CommonTokenStream tokens = tryLexing(new CaseInsensitiveInputStream(CharStreams.fromString(s)));
        assertEquals(2, tokens.size());
    }

    private CommonTokenStream tryLexing(CharStream stream) {
        ApexLexer lexer = new ApexLexer(stream);
        lexer.removeErrorListeners(); // Avoid distracting "token recognition error" stderr output
        lexer.addErrorListener(new BaseErrorListener() {
            @Override
            public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol, int line,
                int charPositionInLine, String msg, RecognitionException e) {
                throw new IllegalStateException(String.format("Syntax error on line %d:%d: %s.",
                    line, charPositionInLine, msg));
            }
        });
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        tokens.fill();
        return tokens;
    }
~~~

Is this a by design or a bug? The Apex language is case-insensitive but that shouldn't affect these string values.

Notes:
* Upgrading ANTLR from 4.9.1 to 4.13.2 does not solve it, but it's still good practice
* Lexing with `CommonTokenStream` works correctly for literal non-ASCII Unicode characters like `'François'`

**Comment by adangel** [comment]
ok, the problem would be that the HexCharacters in the grammar only allow lowercase characters:

https://github.com/apex-dev-tools/apex-parser/blob/eb37247dfb98dcbd287ba65c7558a5f9bde779ad/antlr/ApexLexer.g4#L313

That's why `String s = "'Fran\\u00E7ois'";` produces this syntax error, but `String s = "'Fran\\u00e7ois'";` should work though...

**Comment by wahajenius** [comment]
That makes sense. Then I would suggest to change it to `[0-9a-fA-F]` as done by ANTLR's own [Apex](https://github.com/antlr/grammars-v4/blob/master/apex/apex.g4#L959) and [Java](https://github.com/antlr/grammars-v4/blob/master/java/java/JavaLexer.g4#L223) grammars.
